export const DASHBOARD_I18N = {
  en: {
    dashboard: "Dashboard",
    greeting: "Hello, {name}",
    dateRange: "Date Range",
    selectDateRange: "Select date range",
    filter: "Filter",
    quickSelect: "Quick Select",
    reset: "Reset",
    applyFilter: "Apply Filter",
    groupId: "Group ID",
    company: "Company",
    currency: "Currency",
    all: "All",
    period: "Period",
    today: "Today",
    yesterday: "Yesterday",
    thisWeek: "This Week",
    lastWeek: "Last Week",
    thisMonth: "This Month",
    lastMonth: "Last Month",
    thisYear: "This Year",
    earnings: "Earnings",
    profit: "Profit",
    expenses: "Expenses",
    netProfit: "Net Profit",
    netProfitChart: "Net Profit",
    thanLastMonth: "than last month",
    vsLastMonth: "vs last month",
    overview: "Overview",
    swipe: "Swipe",
    trendChart: "Trend Chart",
    statistics: "Statistics",
    currencyDistribution: "Currency Distribution",
    currencies: "Currencies",
    rate: "Rate",
    shareOfTotal: "Share of total",
    breakdownCurrency: "Currency",
    breakdownAmount: "Amount",
    breakdownOriginalAmount: "Original Amount",
    breakdownRate: "Exchange Rate",
    currencyBreakdown: "Currency breakdown",
    multiCurrencyNote: "Includes multi-currency conversion",
    loading: "Loading...",
    loadError: "Failed to load dashboard",
    noData: "No data for this period",
    logout: "Logout",
    navHome: "Home",
    navReport: "Report",
    navTransaction: "Transaction",
    navMore: "More",
    to: "to",
  },
  zh: {
    dashboard: "仪表盘",
    greeting: "你好，{name}",
    dateRange: "日期范围",
    selectDateRange: "选择日期范围",
    filter: "筛选",
    quickSelect: "快速选择",
    reset: "重置",
    applyFilter: "应用筛选",
    groupId: "Group ID",
    company: "公司",
    currency: "币种",
    all: "全部",
    period: "周期",
    today: "今天",
    yesterday: "昨天",
    thisWeek: "本周",
    lastWeek: "上周",
    thisMonth: "本月",
    lastMonth: "上月",
    thisYear: "今年",
    earnings: "收益",
    profit: "利润",
    expenses: "支出",
    netProfit: "净利润",
    netProfitChart: "净利润",
    thanLastMonth: "较上月同期",
    vsLastMonth: "对比上月",
    overview: "概览",
    swipe: "滑动",
    trendChart: "趋势图",
    statistics: "统计",
    currencyDistribution: "币种分布",
    currencies: "币种",
    rate: "汇率",
    shareOfTotal: "占比",
    breakdownCurrency: "币种",
    breakdownAmount: "金额",
    breakdownOriginalAmount: "原币金额",
    breakdownRate: "汇率",
    currencyBreakdown: "币种明细",
    multiCurrencyNote: "含多币种换算",
    loading: "加载中...",
    loadError: "仪表盘加载失败",
    noData: "该周期暂无数据",
    logout: "退出",
    navHome: "首页",
    navReport: "报表",
    navTransaction: "交易",
    navMore: "更多",
    to: "至",
  },
};

export function dashboardLabel(i18n, key) {
  const map = {
    today: i18n.today,
    yesterday: i18n.yesterday,
    thisWeek: i18n.thisWeek,
    lastWeek: i18n.lastWeek,
    thisMonth: i18n.thisMonth,
    lastMonth: i18n.lastMonth,
    thisYear: i18n.thisYear,
  };
  return map[key] || key;
}
