export const LOGIN_I18N = {
  en: {
    admin: "Admin",
    member: "Member",
    companyPlaceholder: "Company / Group ID",
    accountPlaceholder: "Account Id",
    usernamePlaceholder: "Username",
    passwordPlaceholder: "Password",
    rememberMe: "Remember me",
    forgotPassword: "Forget Password?",
    login: "Login",
    loggingIn: "Logging in...",
    notice: "Notice",
    loginFailed: "Login failed",
    loginError: "An error occurred during login",
    loginServerError: "Server error (HTTP {status}). Database may be misconfigured on the server.",
    loginInvalidResponse: "Server returned an invalid response. Check database config on EC2.",
    confirm: "Confirm",
    maintenanceLabel: "System Maintenance:",
  },
  zh: {
    admin: "管理员",
    member: "会员",
    companyPlaceholder: "公司 / 集团 ID",
    accountPlaceholder: "账号 ID",
    usernamePlaceholder: "用户名",
    passwordPlaceholder: "密码",
    rememberMe: "记住我",
    forgotPassword: "忘记密码？",
    login: "登录",
    loggingIn: "登录中...",
    notice: "提示",
    loginFailed: "登录失败",
    loginError: "登录时发生错误",
    loginServerError: "服务器错误 (HTTP {status})。请检查 EC2 数据库配置是否已导入。",
    loginInvalidResponse: "服务器返回异常。请在 EC2 上检查 includes/config.local.php 与 MySQL。",
    confirm: "确认",
    maintenanceLabel: "系统维护中:",
  },
};

export const RESET_PASSWORD_I18N = {
  en: {
    pageTitle: "Reset Password",
    companyPlaceholder: "Company / Group ID (or Owner Code)",
    emailPlaceholder: "Enter your email address",
    tacPlaceholder: "TAC",
    send: "SEND",
    sending: "Sending...",
    newPasswordPlaceholder: "New Password",
    confirmPasswordPlaceholder: "Confirm New Password",
    resetButton: "Reset Password",
    resetting: "Resetting...",
    backToLogin: "Back to Login",
    notice: "Notice",
    success: "Success",
    confirm: "Confirm",
    companyIdFirst: "Please enter Company ID first",
    emailFirst: "Please enter your email address first",
    invalidEmailFormat: "Please enter a valid email address",
    tacSent: "TAC code has been sent to your email",
    verifyCodeLine: "Your verification code:",
    tacFailed: "Failed to send TAC. Please try again.",
    networkError: "Network error. Please try again.",
    passwordsNoMatch: "Passwords do not match",
    enterTac: "Please enter the TAC code",
    companyEmailRequired: "Company ID and email are required",
    resetSuccess: "Password reset successful! Please sign in with your new password.",
    resetFailed: "Failed to reset password. Please try again.",
    switchLang: "Switch language",
  },
  zh: {
    pageTitle: "重置密码",
    companyPlaceholder: "公司 / 集团 ID（或业主代码）",
    emailPlaceholder: "请输入邮箱地址",
    tacPlaceholder: "验证码（TAC）",
    send: "发送",
    sending: "发送中...",
    newPasswordPlaceholder: "新密码",
    confirmPasswordPlaceholder: "确认新密码",
    resetButton: "重置密码",
    resetting: "提交中...",
    backToLogin: "返回登录",
    notice: "提示",
    success: "成功",
    confirm: "确认",
    companyIdFirst: "请先填写公司 / 集团 ID",
    emailFirst: "请先填写邮箱地址",
    invalidEmailFormat: "请输入有效的邮箱地址",
    tacSent: "验证码已发送至您的邮箱",
    verifyCodeLine: "您的验证码：",
    tacFailed: "验证码发送失败，请稍后重试。",
    networkError: "网络异常，请稍后重试。",
    passwordsNoMatch: "两次输入的密码不一致",
    enterTac: "请填写验证码（TAC）",
    companyEmailRequired: "请填写公司 ID 与邮箱",
    resetSuccess: "密码重置成功！请使用新密码登录。",
    resetFailed: "密码重置失败，请稍后重试。",
    switchLang: "切换语言",
  },
};

export const SECONDARY_VERIFY_I18N = {
  en: {
    title: "Secondary Password Verification",
    lead: "Please enter your 6-digit secondary password to continue",
    placeholder: "Enter 6-digit password",
    verify: "Verify",
    verifying: "Verifying...",
    digitsSix: "Please enter exactly 6 digits",
    genericError: "An error occurred. Please try again.",
    switchLang: "Switch language",
    backToLogin: "Back to login",
  },
  zh: {
    title: "二级密码验证",
    lead: "请输入 6 位数字二级密码",
    placeholder: "请输入 6 位数字密码",
    verify: "验证",
    verifying: "验证中...",
    digitsSix: "请输入完整的 6 位数字",
    genericError: "发生错误，请稍后重试。",
    switchLang: "切换语言",
    backToLogin: "返回登录",
  },
};
